# Generated by Django 4.1.7 on 2023-05-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Store", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sex",
            field=models.CharField(
                choices=[("M", "Для мужчин"), ("W", "Для женщин"), ("U", "Унисекс")],
                max_length=1,
                verbose_name="Пол",
            ),
        ),
    ]
