# Generated by Django 4.1.7 on 2023-05-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Store", "0006_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=500, verbose_name="Описание"),
        ),
    ]
